name = "FewSpecialFunctions"
uuid = "6fcbd3ca-4273-49c4-98b3-81b765566de6"
version = "0.1.12"
authors = ["Martin Mikkelsen"]

[deps]
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[weakdeps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

[extensions]
FewSpecialFunctionsForwardDiffExt = "ForwardDiff"

[compat]
Aqua = "0.8.12"
DelimitedFiles = "1.9.1"
ForwardDiff = "1.3.2"
HypergeometricFunctions = "0.3.28"
QuadGK = "2.4.2"
SpecialFunctions = "2.1.2"
Test = "1.10.0"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test", "DelimitedFiles", "ForwardDiff"]
