name = "FewSpecialFunctions"
uuid = "6fcbd3ca-4273-49c4-98b3-81b765566de6"
authors = ["Martin Mikkelsen"]
version = "0.1.3"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
BenchmarkTools = ">=1.3.2"
Documenter = ">=0.27.24"
LaTeXStrings = ">=1.3"
Plots = ">=1.12.4"
QuadGK = ">=2.4.2"
SpecialFunctions = ">=2.1.2"
julia = ">=1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[docs]
repo = "https://github.com/MartinMikkelsen/FewSpecialFunctions.jl"
branch = "gh-pages"
